function(display_help_text)
    message("BUILD_SHARED_LIBS  Set this variable to True for dynamic libraries and False for staic libraries")
    message("WXT_EXAMPLES       Set to true to build examples")
    message("WXT_WX_VERSION     Set to the desired version of the wxWidgets library")
endfunction()
